# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-11 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10, verbose_name='昵称')),
                ('username', models.CharField(max_length=15, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='账户密码')),
                ('status', models.PositiveIntegerField(choices=[(0, '未注册'), (1, '已注册')], default=1, verbose_name='注册状态')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户注册表',
                'verbose_name_plural': '用户注册表',
                'db_table': 'Register',
                'ordering': ['-id'],
            },
        ),
    ]
