# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-11 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='nickname',
            field=models.CharField(max_length=10, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '已注册'), (0, '未注册')], default=1, verbose_name='注册状态'),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=15, unique=True, verbose_name='用户名'),
        ),
    ]
